
spring:
  datasource:
    url: jdbc:mysql://${TODO_MYSQL_HOST}:${TODO_MYSQL_PORT}/${TODO_DATA_BASE_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${TODO_MYSQL_USERNAME}
    password: ${TODO_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
