
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  messages:
    basename: messages, errors

application:
  join-base-point: 1000000000